/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://tzjkugotcrhejpf2gi4kgluxl4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-upjmdfsic5gqdpucnllwau4d7q",
    "aws_cognito_identity_pool_id": "us-west-2:40a02966-c1a0-44bc-a744-04c4d4109c6b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_4wG9xWe6X",
    "aws_user_pools_web_client_id": "acmr9gk8fdgqg7gvjt7grfnf5",
    "oauth": {}
};


export default awsmobile;
